config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'home#index'
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  { class_name: 'User' }.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  get '/about', to: 'home#about'

  get '/services/:id/orders/new', to: 'orders#new'

  get '/services/search', to: 'services#search', as: :search

  post '/orders/new', to: 'orders#create', as: :service_order

  resources :start_time

  resources :users do
    resources :services, shallow: true
    resources :companies
  end

  resources :companies do
    resources :comments
  end

  resources :orders

  resources :services do
    resources :orders, shallow: true
    resources :time_limits, shallow: true
    resources :comments

    collection do
      get :search
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :customer
      can :read, :all
    elsif user.has_role? :owner
      can :manage, Company, user_id: user.id
      can :manage, Service, user_id: user.id
      can :manage, TimeLimit, user_id: user.id
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Avatar

  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
  include Avatar

  has_one_attached :avatar

  has_many :services, dependent: :destroy
  has_one :address, as: :addressable
  has_many :comments, as: :commentable
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :company
end

app/models/order.rb
class Order < ApplicationRecord
  include Calendarable

  belongs_to :user
  belongs_to :service
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/service.rb
class Service < ApplicationRecord
  include Searchable
  include Avatar

  paginates_per 3

  has_one_attached :avatar

  belongs_to :company
  has_many :orders
  has_many :users, through: :orders, dependent: :destroy
  has_one :time_limit, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/time_limit.rb
class TimeLimit < ApplicationRecord
  belongs_to :user
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  devise :registerable
  include Avatar

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.find_or_create_from_auth_hash(auth)
    where(provider: auth.provider, uid: auth.uid, email: auth.info.email).first_or_create! do |user|
      user.provider = auth&.provider
      user.uid = auth&.uid
      user.email = auth&.info&.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  has_one_attached :avatar

  has_many :orders
  has_many :services, through: :orders
  has_one :address, as: :addressable
  has_many :companies
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy]
  load_and_authorize_resource only: %i[new destroy edit update]

  include ServicesHelper

  def show
    @user = current_user
    @company = Company.find(set_service.company_id)
  end

  def new
    @service = Service.new
    @user_companies = current_user_companies
  end

  def create
    allowed_params = service_params
    @service = Service.new(allowed_params)
    @service.user_id = current_user.id

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, location: @service }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render layout: false }
    end
  end

  def edit
    @user_companies = current_user_companies
  end

  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    query = params[:search_services].presence && params[:search_services][:query]

    @services = Service.search(query) if query
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:name, :description, :avatar, :company_id, :user_id)
  end

  def get_comments
    @comments = @service.comments
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def readable_time(time)
    time
  end

  def author_of(record)
    user_signed_in? && current_user.id == record.user_id
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompanyHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
  def current_user_companies
    arr = Company.where(user_id: current_user.id)
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/services/_form.html.haml
= simple_form_for(@service) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  %h1.company-title.text-center Your Service
  .service-form-control.title
    = f.input :name, :placeholder => "Write name of your service"
    = f.input :description, :placeholder => "Tell us what you do"
    = f.file_field :avatar
    = f.label "Select one your company:"
    = f.select :company_id, @user_companies.map {|el| [el.name, el.id] }
    .service-form-actions
      = f.button :submit, 'Create service', class: "btn btn-primary"

app/views/services/destroy.js.erb
document.activeElement.parentElement.innerHTML = ("<%= j(render(partial: 'home/index', locals: { service: @service })) %>")

app/views/services/edit.html.haml
.service-create.text-center
  %h1.title Editing
  = render 'form', service: @service
  = link_to 'Show', @service, class: "btn btn-primary"
  |
  = link_to 'Back', root_path, class: "btn btn-primary"
  = link_to 'Edit Time Limit', edit_time_limit_path(@service.time_limit), class: "btn btn-primary"

app/views/services/new.html.haml
.service-create
  = render 'form', service: @service

app/views/services/search.html.haml
%body
  %section.section-services
    .container
      .row.justify-content-center.text-center
        .col-md-10.col-lg-8
          .header-section
            %h1= t(".welcome", name: "#{current_user.name}")
            = form_for :search_services, url: search_services_path, method: :get do |form|
              = form.text_field :query, value: params[:search_services].presence && params[:search_services][:query]
              = form.submit 'Search'
              .row
              - @services.each do |service|
                .single-service
                  .part-1
                    %i.fab.fa-500px
                    %h3.title 
                      = service.name
                  .part-2
                    %p.description 
                      = service.description
                    %a{:href => "#"}
                      %i.fas.fa-arrow-circle-right>
                      %a.card-link{:href => "/services/#{service.id}"}= t(".Read more")
              .paginator-block
                = paginate @services
              .service-block

app/views/services/show.html.haml
#service-section
  .container
  %body.all-color
    %h3.service-title.text-center= @service.name
    .container
      %body
        .row.attributes-list
          .col-4
          - if @service.avatar.attached?
            = image_tag(@service.avatar_thumbnail, class: "rounded-circle") 
          - else 
            = image_tag("undefigned.jpg", class: "rounded-circle") 
        .row
          .col-4
            %br
            %ul.attributes-list
              %li
                .attribute-name Company:
                = link_to "#{@service.company&.name}", "/users/#{current_user.id}/companies/#{@service.company.id}", class: 'attribute-link'
              %li
                .attribute-name Service Description:
              %h8.text-justify= @service.description
              %li
              - if can? :manage, @service || current_user.has_role?(:admin)
                %hr.new5
                  .service-statistics
                  %h3.profile-title Order Statistic
                  .diagrams
                    .diagrams-item
                      %hr.new5
                      = column_chart @service.orders.group(:user).count.map { |item| [item[0].name, item[1]] }, donut: true
                      .count=@service.orders.count
                      .panel-label Orders
          .col-8
            %br
            .attribute-name Company Description:
            %h8.text-justify= @service.company.description
            %br
            %br
            %br
              - if can? :manage, @service || current_user.has_role?(:admin)
                = link_to 'Destroy', @service, method: :delete, class: "btn btn-primary"
              - if can? :manage, @service || current_user.has_role?(:admin)
                = link_to 'Edit', "/services/#{@service.id}/edit", class: "btn btn-primary"
            %br 
              - if (@service.user_id == current_user.id || current_user.has_role?(:admin)) && @service.time_limit.nil?
                = link_to 'Create limit for service', "/services/#{@service.id}/time_limits/new", class: "btn btn-primary"
            %br
              = link_to 'Make order', "/services/#{@service.id}/orders/new", class: "btn btn-primary" if @service.time_limit != nil
            %br
              %label="Unfortunately this service has not started working yet" if @service.time_limit == nil
        