config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'home#index'
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  { class_name: 'User' }.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  get '/about', to: 'home#about'

  get '/services/:id/orders/new', to: 'orders#new'

  get '/services/search', to: 'services#search', as: :search

  post '/orders/new', to: 'orders#create', as: :service_order

  resources :start_time

  resources :users do
    resources :services, shallow: true
    resources :companies
  end

  resources :companies do
    resources :comments
  end

  resources :orders

  resources :services do
    resources :orders, shallow: true
    resources :time_limits, shallow: true
    resources :comments

    collection do
      get :search
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :customer
      can :read, :all
    elsif user.has_role? :owner
      can :manage, Company, user_id: user.id
      can :manage, Service, user_id: user.id
      can :manage, TimeLimit, user_id: user.id
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Avatar

  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
  include Avatar

  has_one_attached :avatar

  has_many :services, dependent: :destroy
  has_one :address, as: :addressable
  has_many :comments, as: :commentable
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :company
end

app/models/order.rb
class Order < ApplicationRecord
  include Calendarable

  belongs_to :user
  belongs_to :service
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/service.rb
class Service < ApplicationRecord
  include Searchable
  include Avatar

  paginates_per 3

  has_one_attached :avatar

  belongs_to :company
  has_many :orders
  has_many :users, through: :orders, dependent: :destroy
  has_one :time_limit, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/time_limit.rb
class TimeLimit < ApplicationRecord
  belongs_to :user
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  devise :registerable
  include Avatar

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.find_or_create_from_auth_hash(auth)
    where(provider: auth.provider, uid: auth.uid, email: auth.info.email).first_or_create! do |user|
      user.provider = auth&.provider
      user.uid = auth&.uid
      user.email = auth&.info&.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  has_one_attached :avatar

  has_many :orders
  has_many :services, through: :orders
  has_one :address, as: :addressable
  has_many :companies
end

app/controllers/time_limits_controller.rb
class TimeLimitsController < ApplicationController
  before_action :time_limit, only: %i[show edit update destroy]

  load_and_authorize_resource

  include Duration

  def index
    @time_limits = TimeLimit.all
  end

  def show; end

  def new
    @time_limit = TimeLimit.new
    @service = Service.find(params[:service_id])

    authorize! :new, TimeLimit do |_time_limit|
      @service.user_id == current_user.id
    end
  end

  def edit; end

  def create
    allowed_params = time_limit_params
    @time_limit = TimeLimit.new(allowed_params)
    @time_limit.user = current_user
    @time_limit.service_id = params[:service_id]

    respond_to do |format|
      if @time_limit.save
        format.html { redirect_to @time_limit, notice: 'Time limit was successfully created.' }
        format.json { render :show, status: :created, location: @time_limit }
      else
        format.html { render :new }
        format.json { render json: @time_limit.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @time_limit.update(time_limit_params)
        format.html { redirect_to @time_limit, notice: 'Time limit was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_limit }
      else
        format.html { render :edit }
        format.json { render json: @time_limit.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @time_limit.destroy
    respond_to do |format|
      format.html { redirect_to time_limits_url, notice: 'Time limit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def time_limit
    @time_limit = TimeLimit.find(params[:id])
  end

  def time_limit_params
    params.require(:time_limit).permit(:start_time, :end_time, :length, :service_id, :user_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompanyHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
  def current_user_companies
    arr = Company.where(user_id: current_user.id)
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionHelper
end

app/helpers/time_limits_helper.rb
module TimeLimitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/time_limits/_form.html.haml
= simple_form_for([@service, @time_limit]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs.title
    = f.input :start_time
    = f.input :end_time
    = f.input :length
    = f.label "Owner is #{current_user.name}"
  .form-actions
    = f.button :submit, class: "btn btn-primary"

app/views/time_limits/create.html.haml
%h1 TimeLimits#create
%p Find me in app/views/time_limits/create.html.erb

app/views/time_limits/edit.html.haml
.black.text-center
  %h1.title Editing Time Limit
  = render 'form', time_limit: @time_limit
  = link_to 'Show', @time_limit, class: "btn btn-primary"
  |
  = link_to 'Back', time_limit_path, class: "btn btn-primary"

app/views/time_limits/index.html.haml
.black.text-left
  %p.title#notice= notice
  %h1.title Time Limits
  %table
    %thead
      %tr
        %th.title Start time
        %th.title End time
        %th.title User
        %th.title Service
        %th.title{:colspan => "3"}
    %tbody
      - @time_limits.each do |time_limit|
        %tr
          %td.title= time_limit.start_time
          %td.title= time_limit.end_time
          %td.title= time_limit.user.name
          %td.title= time_limit.service.name
          %td.title= link_to 'Show', time_limit
          %td.title= link_to 'Edit', edit_time_limit_path(time_limit)
          %td.title= link_to 'Destroy', time_limit, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to 'New Time Limit', new_service_time_limit_path, class: "btn btn-primary"

  

app/views/time_limits/new.html.haml
.black.text-left
  %h1.title New Time Limit
  = render 'form', time_limit: @time_limit
  = link_to 'Back', service_time_limits_path, class: "btn btn-primary"

app/views/time_limits/show.html.haml
.black.text-center
  %p.title#notice= notice
  %p.title
    %strong Start time:
    = @time_limit.start_time
  %p.title
    %strong End time:
    = @time_limit.end_time
  %p.title
    %strong User:
    = @time_limit.user.name
  %p.title
    %strong Service:
    = @time_limit.service.name
  = link_to 'Edit', edit_time_limit_path(@time_limit), class: "btn btn-primary"
  |